/*
-- Query: select * from feedback
LIMIT 0, 10

-- Date: 2021-02-24 01:18
*/
INSERT INTO `feedback` (`id`,`buyer_id`,`menu_item_id`,`review`,`rating`,`created_date`,`updated_date`) VALUES (1,2,18,'Good selection of restaurants, and discounts seem plentiful. But the app itself is bad. Order status not updating correctly, map doesnt have the needed landmarks to pin, the order history is horrendous, and the driver chat is so buggy, overall look and feel of the app is ok but can be cluttered and messy. Also, any accidental closure one of their module can possibly result into either an error or an inconvenient issue for that page, that includes the customer service chat, driver chat.',5,'2020-09-21 20:18:46','2020-09-21 20:18:46');
INSERT INTO `feedback` (`id`,`buyer_id`,`menu_item_id`,`review`,`rating`,`created_date`,`updated_date`) VALUES (2,2,22,'Highly Recommended',5,'2020-09-21 20:18:46','2020-09-21 20:18:46');
INSERT INTO `feedback` (`id`,`buyer_id`,`menu_item_id`,`review`,`rating`,`created_date`,`updated_date`) VALUES (3,2,24,'Overall, opting to order food from this app is helpful and there are other cheap options. However along the way the payment system is glitches from time to time. I can\'t checkout my food and I don\'t get any delivery. I hope this can be fixed soon. It\'s frustrating. Thank you',5,'2020-09-21 20:18:46','2020-09-21 20:18:46');
INSERT INTO `feedback` (`id`,`buyer_id`,`menu_item_id`,`review`,`rating`,`created_date`,`updated_date`) VALUES (4,2,18,'The items in a restaurant are not clickable anymore. There are descriptions of foods/clickable that are cut out by \"...\". Make the items clickable again so when people want to try out a new restaurant, they\'ll be able to see the full description of the foods/drinks.',5,'2020-09-21 20:19:14','2020-09-21 20:19:14');
INSERT INTO `feedback` (`id`,`buyer_id`,`menu_item_id`,`review`,`rating`,`created_date`,`updated_date`) VALUES (5,2,45,'Highly Recommended',5,'2020-09-22 13:12:55','2020-09-22 13:12:55');
INSERT INTO `feedback` (`id`,`buyer_id`,`menu_item_id`,`review`,`rating`,`created_date`,`updated_date`) VALUES (6,2,45,'Nice',5,'2020-09-22 13:13:54','2020-09-22 13:13:54');
INSERT INTO `feedback` (`id`,`buyer_id`,`menu_item_id`,`review`,`rating`,`created_date`,`updated_date`) VALUES (7,2,32,'Highly Recommended',5,'2020-09-22 13:16:30','2020-09-22 13:16:30');
INSERT INTO `feedback` (`id`,`buyer_id`,`menu_item_id`,`review`,`rating`,`created_date`,`updated_date`) VALUES (8,2,18,'Nice and easy app to use. Below some of my suggestions 1. Please include \"Wishlist\" option for both Restaurants and Food items for ease of access as it is timetaking to search or browse among piles of items at a time. 2. Please consider \"Points\" for customers like CityRewards, Grab meaning the more we order the more points we earn and the more we enjoy in an exchange of points for the orders in a set-out rule. 3. Please include function of \"Upload Photos\" when giving rating after the successful purchase. 4. Promotions - setting level of customers based on points/orders, Birthday promotions, etc. 5. Please add availability of maximizing the Map in order to clearly track the rider bringing the order. Thanks a lot.',5,'2020-09-22 13:16:30','2020-09-22 13:16:30');
INSERT INTO `feedback` (`id`,`buyer_id`,`menu_item_id`,`review`,`rating`,`created_date`,`updated_date`) VALUES (9,2,18,'The app is good but I hope they could add a feature where we could add items from different restaurants all in one order, additional payment might be added though that feature would be good. They should also have a cancel option within a minutes or 30 seconds from ordering so buyers have options.',5,'2020-09-22 13:16:30','2020-09-22 13:16:30');
INSERT INTO `feedback` (`id`,`buyer_id`,`menu_item_id`,`review`,`rating`,`created_date`,`updated_date`) VALUES (10,2,18,'Highly Recommended',5,'2020-09-22 13:16:30','2020-09-22 13:16:30');
